#!/usr/bin/env python3
"""Emit the divergence-n2 scenario grid: ops-per-side x edit-locality.

One TOML file per cell of the RQ-1 offline-divergence sweep. Each cell is a
partition-heal with **singleton groups** (`[{nodes=[0]}, {nodes=[1]}]`), so the
two replicas diverge independently for `ops_per_group` text-splice ops and the
heal->convergence measurement times the merge.

The grid is generated rather than hand-authored so a cell's filename, its
`name` field, and its `ops_per_group` cannot drift apart -- a mismatch there
looks like a real result rather than a typo.

    python3 scenarios/gen-divergence-grid.py            # write scenarios/*.toml
    python3 scenarios/gen-divergence-grid.py --check    # verify on-disk == generated
    just gen-scenarios

Writing is idempotent: re-running over an unchanged grid rewrites identical
bytes. `--check` is the CI-friendly form -- it exits non-zero if any file is
missing or stale, without touching the working tree.
"""

import argparse
import sys
from pathlib import Path

# Ops applied by *each* side during the partition, as powers of ten. The total
# op count per trial is twice this (two singleton groups).
EXPONENTS = [2, 3, 4, 5]

# Edit-locality rules, in increasing anchor-contention order. Must match the
# `Locality` variants in crates/orchestrator/src/topology.rs (snake_case).
LOCALITIES = ["append", "random_position", "same_region"]

# One-line gloss per locality, inlined into each cell's header comment.
LOCALITY_BLURB = {
    "append": "each op inserts at the current end -- the low-contention floor",
    "random_position": "each op inserts at a uniformly-random position",
    "same_region": "every op prepends at the same anchor -- maximal contention",
}

SCENARIO_DIR = Path(__file__).resolve().parent


def cell_name(locality: str, exponent: int) -> str:
    return f"divergence-n2-{locality}-1e{exponent}"


def cell_toml(locality: str, exponent: int) -> str:
    """Render one grid cell. Field order matches the hand-written 1e2 cells."""
    ops = 10**exponent
    return f"""\
# Generated by scenarios/gen-divergence-grid.py -- do not edit by hand; re-run
# the generator to refresh. One cell of the RQ-1 offline-divergence grid
# (ops-per-side x edit-locality).
#
# 2 replicas partition into singleton groups, each applies {ops:,} text-splice
# ops, then heal and measure convergence.
#
# locality = {locality}: {LOCALITY_BLURB[locality]}.
name = "{cell_name(locality, exponent)}"

[partition_heal]
node_count = 2
write_pattern = "concentrated"
workload = "text_splice"
locality = "{locality}"
ops_per_group = {ops}

[[partition_heal.groups]]
nodes = [0]

[[partition_heal.groups]]
nodes = [1]
"""


def grid() -> list[tuple[Path, str]]:
    """The full grid as (path, content) pairs, in sweep order."""
    return [
        (SCENARIO_DIR / f"{cell_name(loc, exp)}.toml", cell_toml(loc, exp))
        for loc in LOCALITIES
        for exp in EXPONENTS
    ]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--check",
        action="store_true",
        help="verify the on-disk grid matches the generator; write nothing",
    )
    args = p.parse_args()

    stale: list[Path] = []
    for path, content in grid():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(content)
            print(f"{'updated' if current is not None else 'wrote'} {path.name}")

    if args.check and stale:
        print(
            "error: divergence grid is stale or incomplete; run "
            "`just gen-scenarios`. Affected:",
            file=sys.stderr,
        )
        for path in stale:
            print(f"  {path.name}", file=sys.stderr)
        return 1

    n = len(LOCALITIES) * len(EXPONENTS)
    print(f"divergence grid {'checked' if args.check else 'generated'}: {n} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
