#!/usr/bin/env python3
"""Emit a docker compose YAML for N replicant replicas + otel-collector + prometheus.

Run via `just smoke-docker <scenario>`; that recipe parses node_count from the
scenario TOML and pipes the output to `deploy/docker/compose.generated.yaml`.
Can also be invoked directly:

    python3 deploy/docker/gen-compose.py 5 > deploy/docker/compose.generated.yaml
    docker compose -f deploy/docker/compose.generated.yaml up -d --build

The output is functionally identical to the hand-maintained compose.yaml this
script replaced (n=5). Build contexts resolve relative to deploy/docker/, so
the output file must live there.
"""

import argparse
import sys

import yaml


# PyYAML's default SafeDumper emits anchor/alias refs for repeated objects,
# turning the per-replica common config into `*id001` lines. Disable aliases
# so each service is fully self-describing — the whole point of generating
# inspectable YAML is that readers don't need to chase references.
class NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):  # noqa: D401, ARG002
        return True


REPLICA_INTERNAL_PORT = 50051
REPLICA_HOST_PORT_BASE = 50051


def replica_service(i: int) -> dict:
    """Service definition for replica-i. Each call returns a fresh dict."""
    return {
        "build": {"context": "../..", "dockerfile": "Dockerfile"},
        "container_name": f"replica-{i}",
        "hostname": f"replica-{i}",
        "command": ["--actor", f"node-{i}", "--port", str(REPLICA_INTERNAL_PORT)],
        "ports": [f"{REPLICA_HOST_PORT_BASE + i}:{REPLICA_INTERNAL_PORT}"],
        "networks": ["replicant"],
        "restart": "no",
        "environment": {"OTEL_EXPORTER_OTLP_ENDPOINT": "http://otel-collector:4317"},
        "depends_on": {"otel-collector": {"condition": "service_started"}},
    }


def build_compose(n: int) -> dict:
    if n < 1:
        raise ValueError(f"node_count must be >= 1, got {n}")

    services: dict[str, dict] = {f"replica-{i}": replica_service(i) for i in range(n)}

    services["otel-collector"] = {
        "image": "otel/opentelemetry-collector-contrib:0.152.0",
        "container_name": "otel-collector",
        "hostname": "otel-collector",
        "networks": ["replicant"],
        "command": ["--config=/etc/otel-collector-config.yaml"],
        "volumes": ["./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro"],
        "ports": ["4317:4317", "8889:8889"],
    }

    services["prometheus"] = {
        "image": "prom/prometheus:v3.11.3",
        "container_name": "prometheus",
        "hostname": "prometheus",
        "networks": ["replicant"],
        "volumes": ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro"],
        "ports": ["9090:9090"],
        "depends_on": {"otel-collector": {"condition": "service_started"}},
    }

    return {
        "name": "replicant",
        "services": services,
        "networks": {"replicant": {"driver": "bridge"}},
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("n", type=int, help="number of replica services to generate")
    args = p.parse_args()

    header = (
        f"# Generated by deploy/docker/gen-compose.py for n={args.n}. Do not edit by hand —\n"
        f"# re-run the generator to refresh. See the script docstring for usage.\n"
    )
    sys.stdout.write(header)
    yaml.dump(
        build_compose(args.n),
        sys.stdout,
        Dumper=NoAliasDumper,
        sort_keys=False,
        default_flow_style=False,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
